config/routes.rb
ECMS::Application.routes.draw do

  
  

  resources :user_sessions, :only =>[:new, :create, :destroy]
  resources :users, :only => [:new, :create, :show]
  resources :newsusers, :id => /.+/
  resources :contacts, :only => [:new, :create]

  match "admin", :to => "Admin#index", :as => "admin"      
  match "login", :to => "User_sessions#new", :as => "login"
	match "logout", :to => "User_sessions#destroy", :as => "logout"
  match "register", :to => "Users#new", :as => "register"
   namespace :admin do
      post 'upload_media' => "Mmanagers#upload_media", :as => "upload_media"
      resources :mmanagers do
        get 'place', :on => :collection
        post 'create_directory', :on => :collection
        get 'show_file', :on => :collection
        get 'del_file', :on => :collection
        get 'del_dir', :on => :collection

      end
    resources :newsletters
    resources :users
    resources :menus
    resources :articles do
      get "act(/:art_act)", :to => "Articles#act", :as => "act"
      get "menu(/:menu_act)", :to => "Articles#menu", :as => "menu"
    end
    resources :galleries do
      resources :images
    end
   end
    get  "admin/configurations", :to => "admin/Configurations#edit", :as => "edit_admin_configuration"
    post "admin/configurations", :to => "admin/Configurations#update", :as => "admin_configuration"
    

  

   match ':id' => "Articles#show", :as => "article"

root :to => "home#index"

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_many :images, :dependent => :destroy
end

app/controllers/admin/galleries_controller.rb
class Admin::GalleriesController < AdminController

  def index
    @galleries = Gallery.all
  end
  
  def new
    @gallery = Gallery.new
  end
  
  def edit
    @gallery = Gallery.find(params[:id])
    @image = Image.new
    @images = Image.find_images_for_gallery(params[:id])

  end
  
  def create
    @gallery = Gallery.new(params[:gallery])
    respond_to do |format|
      if @gallery.save
        format.html {redirect_to admin_galleries_path }
      else
        format.html {redirect_to admin_galleries_path }        
      end
    end
  end
  
  def update
    @gallery = Gallery.find(params[:id])
    respond_to do |format|
      if @gallery.update_attributes(params[:gallery])
        format.html {redirect_to admin_galleries_path }
      else
        format.html {redirect_to admin_galleries_path }
      end
    end
  end

  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy
      respond_to do |format|
        format.html {redirect_to admin_galleries_path }
      end
  end

end

app/views/admin/galleries/edit.html.erb
<p id="title"><i>Edycja galerii</i></p>


<div id="image-box" class="feathered">  
  <%= form_for([:admin, @gallery, @image], :html => {:multipart => true}) do |f| %>
    <p>
      <b><i>Image to gallery/image</i></b><br />
      <%= f.file_field :photo %>
    </p>
    <p>
      <%= f.hidden_field :gallery_id, :value => params[:id]%>
      Opis zdjęcia:<%= f.text_field :name %><br />
      <%= f.hidden_field :position, :value => @images.count+1 %>
    </p>
    <p><%= f.submit %>
    </p>
  <% end %>
</div>






<%= form_for([:admin, @gallery], :html => {:multipart => true}) do |f| %>
<p>
  Nazwa galerii:
  <%= f.text_field :name %>
</p>



<div style="float:left; width: 550px; margin: 0 0 0 5px;">
    <% @images.each do |image| %>
    <div style="float:left; padding: 2px;">
      <div style="width: 150px;">
        <%= image.name %>
      </div>
      <%= image_tag(image.photo.url(:vsmall))%><br />
      <%= link_to "usuń", admin_gallery_image_path(@gallery.id, image.id), :method => :delete, :confirm => "Na pewno chcesz usunąć to zdjęcie?"%>
    </div>
    <% end %>
</div>
<div style="clear:both;"></div>
<br />
  <%= f.submit %><br /><br />
<% end %>

<div style="clear:both;"></div>
<br />
<br />
<br />

app/views/admin/galleries/index.html.erb
<p id="title"><i>Admin Galerie</i></p>
<table>
  <tr id="none">
    <td>Galeria</td>
    <td>Link do galerii</td>
    <td>Nazwa</td>
    <td colspan="2">Akcje</td>
  </tr>
  <% @galleries.each do |gallery| %>
  <tr>
    <td><%= gallery.id %></td>
    <td><%= "{gallery=#{gallery.id}}" %></td>
    <td><%= if gallery.images.first then image_tag gallery.images.first.photo.url(:vsmall) else "" end %></td>
    <td><%= gallery.name %></td>
    <td><%= link_to "Edytuj", edit_admin_gallery_path(gallery) %></td>
    <td><%= link_to "Usuń", admin_gallery_path(gallery), :method => :delete, :confirm => "Jesteś pewien że chcesz usunąć tą galerię?" %></td>
  </tr>
  <% end %>
</table>
<%= link_to "Dodaj Galerię", new_admin_gallery_path %>

app/views/admin/galleries/new.html.erb
<p>new</p>
<% form_for([:admin, @gallery], :html => { :multipart => true } ) do |f| %>

<p>
  Nazwa galerii:
  <%= f.text_field :name %>
</p>
  <%= f.submit %>
<% end %>

<%= link_to "Wróć", admin_galleries_path %>