config/routes.rb
ECMS::Application.routes.draw do

  
  

  resources :user_sessions, :only =>[:new, :create, :destroy]
  resources :users, :only => [:new, :create, :show]
  resources :newsusers, :id => /.+/
  resources :contacts, :only => [:new, :create]

  match "admin", :to => "Admin#index", :as => "admin"      
  match "login", :to => "User_sessions#new", :as => "login"
	match "logout", :to => "User_sessions#destroy", :as => "logout"
  match "register", :to => "Users#new", :as => "register"
   namespace :admin do
      post 'upload_media' => "Mmanagers#upload_media", :as => "upload_media"
      resources :mmanagers do
        get 'place', :on => :collection
        post 'create_directory', :on => :collection
        get 'show_file', :on => :collection
        get 'del_file', :on => :collection
        get 'del_dir', :on => :collection

      end
    resources :newsletters
    resources :users
    resources :menus
    resources :articles do
      get "act(/:art_act)", :to => "Articles#act", :as => "act"
      get "menu(/:menu_act)", :to => "Articles#menu", :as => "menu"
    end
    resources :galleries do
      resources :images
    end
   end
    get  "admin/configurations", :to => "admin/Configurations#edit", :as => "edit_admin_configuration"
    post "admin/configurations", :to => "admin/Configurations#update", :as => "admin_configuration"
    

  

   match ':id' => "Articles#show", :as => "article"

root :to => "home#index"

end

app/models/article.rb
class Article < ActiveRecord::Base
  acts_as_list  
  belongs_to :user
  belongs_to :menu

  validates :title, :presence => true
  
  def to_param
    "#{id}-#{title.parameterize}"
  end
  
  def self.show_publish_on_frontpage
    all(:conditions => {:publish => true, :frontpage => true }, :order => :position)
  end
  
  def self.show_like_list
    all(:order => :position)
  end
  
  def self.show_like_menu_list
    all(:conditions =>{:publish => true, :menu => 1}, :order => :menu_position)
  end
  
  
  
  def self.show_menu_list
    find_by_sql "SELECT articles.id, articles.title, menus.position FROM articles JOIN menus on articles.id = menus.article_id ORDER BY menus.position"
end
  
  
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < AdminController
  before_filter :expire_root, :except => [:index, :show]
  before_filter :expire_all, :only => [:act] # uruchomione na stesty :)  
  def index
    @articles = Article.show_like_list
  end
  
  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def show
    @article = Article.find(params[:id])
  end
  
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
         @article.move_to_top
format.html { redirect_to(admin_articles_path, :notice => 'Article was successfully created.') }
        format.xml  { render :xml => @article, :status => :created, :location => @article }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /admin/article/1
  # PUT /admin/article/1.xml
  def update
    expire_one(params[:id])
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to([:admin, @article], :notice => 'Article was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/article/1
  # DELETE /admin/article/1.xml
  def destroy
    expire_one(params[:id])

    @article = Article.find(params[:id])
    @article.destroy
    @menu = Menu.find_by_article_id(params[:id])
    if !@menu.nil?
      @menu.destroy
    end
    respond_to do |format|
      format.html { redirect_to(admin_articles_url) }
      format.xml  { head :ok }
    end
  end
  
  ################
  def act 
    @article = Article.find(params[:article_id])
    if (params[:art_act] == "f_yes" || params[:art_act] == "f_no")
      if params[:art_act] == "f_no"
        @article.update_attributes(:frontpage => true )
        redirect_to(admin_articles_url)
      else
        @article.update_attributes(:frontpage => false)
        redirect_to(admin_articles_url)
      end
      
    end
    if (params[:art_act] == "true" || params[:art_act] == "false")
      respond_to do |format|
          if @article.update_attributes(:publish => params[:art_act])
            format.html {redirect_to(admin_articles_url)}        
          else
            format.html {redirect_to(admin_articles_url)}
          end
        end 
    elsif params[:art_act] == "up"
      respond_to do |format|
          if @article.move_higher
            format.html {redirect_to(admin_articles_url)}
          else
            format.html {redirect_to(admin_articles_url)}
          end
      end
    elsif params[:art_act] == "down"
      respond_to do |format|
          if @article.move_lower
            format.html {redirect_to(admin_articles_url)}
          else
            format.html {redirect_to(admin_articles_url)}
          end
      end
    elsif params[:art_act] == "yes"
      respond_to do |format|
          @menu = Menu.new(:article_id => Article.find_by_id(params[:article_id]).id)
          if @menu.save
            format.html {redirect_to(admin_articles_url)}
          else
            format.html {redirect_to(admin_articles_url)}
          end
      end
    elsif params[:art_act] == "no"
      respond_to do |format|
         @menu = Menu.find(:first, :conditions => {:article_id => Article.find_by_id(params[:article_id]).id})        
        @menu.destroy
            format.html {redirect_to(admin_articles_url)}
            
          end
      end
  end
  
  def menu
    @article = Article.find(params[:article_id])
    if params[:menu_act] == "yes"    
      @menu = Menu.new(:article_id => Article.find_by_id(params[:article_id]).id)
      @menu.save
      respond_to do |format|
          if @menu.save
            format.html {redirect_to(admin_menus_url)}
          else
            format.html {redirect_to(admin_menus_url)}
          end
      end
    elsif params[:menu_act] == "no"
      respond_to do |format|
        @menu = Menu.find(:first, :conditions => {:article_id => Article.find_by_id(params[:article_id]).id})        
        @menu.destroy
            format.html {redirect_to(admin_menus_url)}
      end
    elsif params[:menu_act] == "up"
      @menu = Menu.find(:first, :conditions => {:article_id => Article.find_by_id(params[:article_id]).id})        
      respond_to do |format|
          if @menu.move_higher
            format.html {redirect_to(admin_menus_url)}
          else
            format.html {redirect_to(admin_menus_url)}
          end
        end
    elsif params[:menu_act] == "down"
      @menu = Menu.find(:first, :conditions => {:article_id => Article.find_by_id(params[:article_id]).id})        
      respond_to do |format|
          if @menu.move_lower
            format.html {redirect_to(admin_menus_url)}
          else
            format.html {redirect_to(admin_menus_url)}
          end
        
        end
      end    
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

#  caches_page :show
  
  def show
    @menu = Article.show_menu_list
    @article = Article.find(params[:id])
    @tags = @article.tag
  end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/views/admin/articles/_form.html.erb
<%= javascript 'tinymce/jquery.tinymce'%>
<%= javascript 'tinymce/tiny_mce'%>
<%= javascript 'tinymce/admin'%>

<p id="title"><i>Admin article new</i></p>
<%= form_for([:admin, @article]) do |f| %>
  <% if @article.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>
    
        <ul>
          <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
    <table>
      <tr id="none">
        <td>
            <b>Tytuł:</b>
            <%= f.text_field :title %>
        </td>
        <td>
            <b>Tagi:</b>
            <%= f.text_field :tag %>
        </td>
      </tr>
      <tr id="none">
        <td>
              <b>Publikacja:</b>
              <%= f.select "publish", options_for_select({ "Tak" => true, "Nie" => false}) %>
        </td>
        <td>
              <b>Skrót:</b>
              <%= f.text_field :head %>
        </td>
      </tr>
    </table>


  <p>
    <b>Treść:</b>
    <%= f.text_area :body, :class => "tinymce" %>
  </p>


  <p>
    <%= f.submit %>
  </p>
  
<% end %>

app/views/admin/articles/edit.html.erb
<p id="title"><i>Edit article</i></p>
<%= render 'form'%>
<p>
<%= link_to "Powrót", admin_articles_path %>
</p>

app/views/admin/articles/index.html.erb
<i>Admin articles</i>
  <p style="display:inline;float:right;"<%= link_to("Dodaj Artykuł", new_admin_article_path)%>
  </p>
<table>
  <tr id="none">
    <th>#id</th>
    <th>position</th>
    <th>Menu?</th>
    <th>FrontPage</th>
    <th>publish</th>
    <th>title</th>
    <th colspan="4">actions</th>
  </tr>
  <% @articles.each do |article| %>
  <tr>
    <td>#<%= article.id %></td>
    <td><%= article.position %></td>
    <td><%= if !Menu.find(:first, :conditions => {:article_id => article.id }).nil? then link_to("Tak", article_act_path(article, "no")) else link_to("Nie", article_act_path(article, "yes")) end  %></td>
      <td><%= if article.frontpage then link_to("Tak", article_act_path(article, "f_yes")) else link_to("Nie", article_act_path(article, "f_no")) end %></td>
    <td><%= link_to("#{article.publish?}", article_act_path(article, "#{!article.publish?}")) %></td>
    <td><%= article.title %></td>
    <td><%= link_to("Up", article_act_path(article, "up"))%> |
        <%= link_to("Down", article_act_path(article, "down"))%>
    </td>
    <td><%= link_to("Pokaż", admin_article_path(article)) %></td>
    <td><%= link_to("Edytuj", edit_admin_article_path(article))%></td>
    <td><%= link_to "Usuń", [:admin, article], :confirm => 'TAK?', :method => :delete %></td>
  </tr>
  <% end %>
</table>

app/views/admin/articles/new.html.erb
<%= render "form"%>

app/views/admin/articles/show.html.erb
<p>
  id:
  <%= @article.id%>
</p>
<p>
  tagi:
  <%= @article.tag%>
</p>

<p>
  publish:
  <%= @article.publish%>
</p>
<p>
  title:
  <%= @article.title%>
</p>
  body:
  <div style="border: solid 1px black;">  
  <%= render_gallery(@article.body) %>
</div>
  
  <%= link_to "Wróć", admin_articles_path %>