config/routes.rb
ECMS::Application.routes.draw do

  
  

  resources :user_sessions, :only =>[:new, :create, :destroy]
  resources :users, :only => [:new, :create, :show]
  resources :newsusers, :id => /.+/
  resources :contacts, :only => [:new, :create]

  match "admin", :to => "Admin#index", :as => "admin"      
  match "login", :to => "User_sessions#new", :as => "login"
	match "logout", :to => "User_sessions#destroy", :as => "logout"
  match "register", :to => "Users#new", :as => "register"
   namespace :admin do
      post 'upload_media' => "Mmanagers#upload_media", :as => "upload_media"
      resources :mmanagers do
        get 'place', :on => :collection
        post 'create_directory', :on => :collection
        get 'show_file', :on => :collection
        get 'del_file', :on => :collection
        get 'del_dir', :on => :collection

      end
    resources :newsletters
    resources :users
    resources :menus
    resources :articles do
      get "act(/:art_act)", :to => "Articles#act", :as => "act"
      get "menu(/:menu_act)", :to => "Articles#menu", :as => "menu"
    end
    resources :galleries do
      resources :images
    end
   end
    get  "admin/configurations", :to => "admin/Configurations#edit", :as => "edit_admin_configuration"
    post "admin/configurations", :to => "admin/Configurations#update", :as => "admin_configuration"
    

  

   match ':id' => "Articles#show", :as => "article"

root :to => "home#index"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 # caches_page :index
  
  def index
    @menu = Article.show_menu_list
    @articles = Article.show_publish_on_frontpage
    @newsuser = Newsuser.new
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%# @current_user.nil?%>
<%# if current_user %>
    <%#= link_to "Logout", logout_path %>
  <%# else %>
    <%#= link_to "Register", register_path %> 
    <%#= link_to "Login", login_path %>
<%# end %>

<% @articles.each do |article| %>
  <p>
    <% if article.first? %>
    <div id="first_article_title">
      <p><%= article.title %></p>
    </div>
      <% else %>
      <div id="article_title">
        <p><%= article.title %></p>
      </div>
    <% end %>
    <%= article.head %>
    <div id="read_more">
      <%= link_to "Czytaj więcej", article_path(article)%>
    </div><br />
  </p>
  <div id="article_spacer"></div>
<% end %>
  