config/routes.rb
ECMS::Application.routes.draw do

  
  

  resources :user_sessions, :only =>[:new, :create, :destroy]
  resources :users, :only => [:new, :create, :show]
  resources :newsusers, :id => /.+/
  resources :contacts, :only => [:new, :create]

  match "admin", :to => "Admin#index", :as => "admin"      
  match "login", :to => "User_sessions#new", :as => "login"
	match "logout", :to => "User_sessions#destroy", :as => "logout"
  match "register", :to => "Users#new", :as => "register"
   namespace :admin do
      post 'upload_media' => "Mmanagers#upload_media", :as => "upload_media"
      resources :mmanagers do
        get 'place', :on => :collection
        post 'create_directory', :on => :collection
        get 'show_file', :on => :collection
        get 'del_file', :on => :collection
        get 'del_dir', :on => :collection

      end
    resources :newsletters
    resources :users
    resources :menus
    resources :articles do
      get "act(/:art_act)", :to => "Articles#act", :as => "act"
      get "menu(/:menu_act)", :to => "Articles#menu", :as => "menu"
    end
    resources :galleries do
      resources :images
    end
   end
    get  "admin/configurations", :to => "admin/Configurations#edit", :as => "edit_admin_configuration"
    post "admin/configurations", :to => "admin/Configurations#update", :as => "admin_configuration"
    

  

   match ':id' => "Articles#show", :as => "article"

root :to => "home#index"

end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  after_create :deliver_now
  after_update :deliver_now
  
  private
  def deliver_now
    if self.delived_now == true then
      Newsuser.all.each do |user|
        NewsletterMailer.news_mailer(user.email, self.body, self.title)
        @newsletter = Newsletter.find(self.id)
        @newsletter.update_attributes(:delived_now => 0, :delived_when => Time.now)
        @newsletter.save
      end
    end
  end
end

app/controllers/admin/newsletters_controller.rb
class Admin::NewslettersController < AdminController
  
  def index
    @newsletters = Newsletter.all
  end
  
  def new
    @newsletter = Newsletter.new
  end
  
  def show
    @newsletter = Newsletter.find(params[:id])
  end
  
  def edit
    @newsletter = Newsletter.find(params[:id])
  end
  
  def create
    @newsletter = Newsletter.new(params[:newsletter])
    respond_to do |format|
      if @newsletter.save
        format.html {redirect_to admin_newsletters_path, :notice => "Newsletter save"}
      else
        format.html {redirect_to admin_newsletters_path, :notice => "save newsletter fail!"}
      end
    end
  end

  def update
    @newsletter = Newsletter.find(params[:id])
    if @newsletter.update_attributes(params[:newsletter])
      redirect_to admin_newsletters_path, :notice => "Newsletter zaktualizowany"
    else
      redirect_to admin_newsletters_path, :notce => "Newsletter nie zaktualizowany!"
    end
  end
  
  def destroy
    @newsletter = Newsletter.find(params[:id])
    @newsletter.destroy
    redirect_to admin_newsletters_path, :notice => "Newsletter usuniety"
  end
  
end

app/helpers/admin/newsletters_helper.rb
module Admin::NewslettersHelper
end

app/views/admin/newsletters/edit.html.erb
<%= javascript 'tinymce/jquery.tinymce'%>
<%= javascript 'tinymce/tiny_mce'%>
<%= javascript 'tinymce/admin'%>

<p>Newsletter</p>
<%= form_for([:admin, @newsletter], :html => { :multipart => true } ) do |f| %>

<p>
  Status<br /> gotowy do wysyłki?
  <%= f.check_box :ready %>
</p>
<p>
Wysłać natychmiast po zapisaniu?
  <%= f.check_box :delived_now %>
</p>
  <!--  Kiedy wysłać ? -->
  <%#= f.date_select :delived %>
<p>
Tytuł newslettera:
  <%= f.text_field :title %>
</p>

<p>
  Newsletter:
  <%= f.text_area :body %>
</p>
  <%= f.submit "Edytuj Newsletter" %>
<% end %>

<%= link_to "Wróć", admin_newsletters_path %>

app/views/admin/newsletters/index.html.erb
<p id="title"><i>Admin Newsletter</i></p>
<table>
  <tr id="none">
    <td>#id</td>
    <td>Tytuł</td>
    <td>Status: gotowy</td>
    <td>Wysłany?</td>
    <td colspan="3">Akcje</td>
  </tr>
  <% @newsletters.each do |newsletter| %>
  <tr>
    <td><%= newsletter.id %></td>
    <td><%= newsletter.title %></td>
    <td><%= newsletter.ready ? "Tak" : "Nie" %></td>
    <td><%= newsletter.delived_when? ? "Tak #{newsletter.delived_when}" : "Nie" %></td>
    <td><%= link_to "Pokaż", admin_newsletter_path(newsletter) %></td>
    <td><%= link_to "Edytuj", edit_admin_newsletter_path(newsletter) %></td>
    <td><%= link_to "Usuń", admin_newsletter_path(newsletter), :method => :delete, :confirm => "Na pewno usunac newsletter?" %></td>
  </tr>
  <% end %>
</table>
<%= link_to "Dodaj Newsletter", new_admin_newsletter_path %>

app/views/admin/newsletters/new.html.erb
<%= javascript 'tinymce/jquery.tinymce'%>
<%= javascript 'tinymce/tiny_mce'%>
<%= javascript 'tinymce/admin'%>

<p>Newsletter</p>
<% form_for([:admin, @newsletter], :html => { :multipart => true } ) do |f| %>

<p>
  Status gotowy do wysyłki?
  <%= f.check_box :ready, :checked => false %>
</p>
<p>
  Kiedy wysłać ?
  <%= f.date_select :delived %>
</p>
  <!--  Wysłać natychmiast po zapisaniu? -->
  <%# f.check_box :delived_now %>

<p>
  Wysłany:
  <%# f.date_select :delived_when %>
</p>

<p>
Tytuł newslettera:
  <%= f.text_field :title %>
</p>

<p>
  Newsletter:
  <%= f.text_area :body %>
</p>
  <%= f.submit "Dodaj newsletter" %>
<% end %>

<%= link_to "Wróć", admin_newsletters_path %>

app/views/admin/newsletters/show.html.erb
<p>
  Status<br /> gotowy do wysyłki?
  <%= @newsletter.ready %>
</p>
<p>
Tytuł newslettera:
  <%= @newsletter.title %>
</p>
<hr />
<p>
  Newsletter:
  <%= @newsletter.body.html_safe %>
</p>
<%= link_to "Wróć", admin_newsletters_path %>